### ISSUE TITLE
Collection of Arakoon check changes

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#383]
This is a collections of Arakoon test changes:
- [x] Move the current  arakoon (cluster) checks to a cluster level so these can be used by internal and external arakoons (https://github.com/openvstorage/openvstorage-health-check/issues/345)
- [x]  Add/extend arakoon collapse check with available disk space verification for local collapse (https://github.com/openvstorage/openvstorage-health-check/issues/222)
- [x]  check node health of all nodes in the cluster (https://github.com/openvstorage/openvstorage-health-check/issues/324)
- [x] Integrate tcp connections of arakoon check in healthcheck (https://github.com/openvstorage/openvstorage-health-check/issues/95)
- [x] NSM & ABM load #101

**Comment by saelbrec** [comment]
@JeffreyDevloo ,

#222 can be taken up in the collapse instead of healthCheck.
#324 and #101 we can continue

**Comment by JeffreyDevloo** [comment]
Part of the next 3.4 release

**Comment by wimpers** [comment]
Should this ticket be in state_validation?

**Comment by JeffreyDevloo** [comment]
It can be, depends if the state_verification actually means something

**Comment by simonOpenV** [comment]
Mark as state codecomplete?

**Comment by JeffreyDevloo** [comment]
All items on the checklist have been done since 3.6.5. Closing
